import type { AlgorithmId, AlgorithmMeta } from '../algorithms/types';

export const ALGORITHM_REGISTRY: Record<AlgorithmId, AlgorithmMeta> = {
  bfs: {
    id: 'bfs',
    name: 'Breadth-First Search',
    short: 'BFS',
    family: 'Uninformed · Queue',
    complexity: { time: 'O(V + E)', space: 'O(V)' },
    optimal: true,
    complete: true,
    weighted: false,
    color: 'accent',
    blurb: 'Level-order traversal from source. Optimal on unweighted graphs. Explores equally in all directions.',
    pseudocode: [
      'function bfs(start, goal):',
      '  Q ← queue([start])',
      '  visited ← { start }',
      '  parent[start] ← null',
      '  while Q not empty:',
      '    u ← Q.dequeue()',
      '    if u = goal: return reconstruct(u)',
      '    for each neighbor v of u:',
      '      if v ∉ visited:',
      '        visited.add(v)',
      '        parent[v] ← u',
      '        Q.enqueue(v)',
    ],
    stepToLine: { enqueue: 11, dequeue: 5, visit: 7, path: 6, done: 6 },
    papers: [
      {
        title: 'The shortest path through a maze',
        authors: 'Moore, E. F.',
        year: 1959,
        url: 'https://dl.acm.org/doi/10.1145/321556.321565',
        venue: 'Int. Symp. on the Theory of Switching',
      },
    ],
    proofSketch:
      'BFS explores nodes in order of distance from the source (level by level). The first time a node is visited, the path that led there has the minimum number of edges, so on unweighted graphs the discovered path is optimal.',
    watchFor: [
      'Unweighted graphs only — every step has cost 1.',
      'Queue order matters: a stack here would produce DFS, which is not optimal.',
      'Watch the level-by-level expansion — every cell at distance d is visited before any cell at distance d+1.',
    ],
  },

  dfs: {
    id: 'dfs',
    name: 'Depth-First Search',
    short: 'DFS',
    family: 'Uninformed · Stack',
    complexity: { time: 'O(V + E)', space: 'O(V)' },
    optimal: false,
    complete: true,
    weighted: false,
    color: 'pink',
    blurb: 'Stack-driven traversal. Explores deeply before backtracking. Does NOT guarantee shortest path.',
    pseudocode: [
      'function dfs(start, goal):',
      '  S ← stack([start])',
      '  visited ← { start }',
      '  parent[start] ← null',
      '  while S not empty:',
      '    u ← S.pop()',
      '    if u = goal: return reconstruct(u)',
      '    for each neighbor v of u:',
      '      if v ∉ visited:',
      '        visited.add(v)',
      '        parent[v] ← u',
      '        S.push(v)',
    ],
    stepToLine: { enqueue: 11, dequeue: 5, visit: 7, path: 6 },
    papers: [],
    proofSketch:
      'DFS does not guarantee the shortest path. It finds A path, not THE shortest path. Useful for maze solving where any solution is acceptable.',
    watchFor: [
      'May find a very long path even when a short one exists.',
      'Stack-based: the last-in cell is processed first (LIFO).',
      'Compare to BFS: DFS explores one branch deeply before backtracking.',
    ],
  },

  dijkstra: {
    id: 'dijkstra',
    name: "Dijkstra's Algorithm",
    short: 'Dijkstra',
    family: 'Uniform-cost search',
    complexity: { time: 'O((V + E) log V)', space: 'O(V)' },
    optimal: true,
    complete: true,
    weighted: true,
    color: 'accent',
    blurb:
      "Greedy expansion by shortest known distance from source. Optimal for non-negative weights. The foundation of A*.",
    pseudocode: [
      'function dijkstra(start):',
      '  for each v ∈ V: dist[v] ← ∞',
      '  dist[start] ← 0',
      '  Q ← min-heap of V keyed by dist',
      '  while Q not empty:',
      '    u ← pop min-dist from Q',
      '    if u = goal: return reconstruct(u)',
      '    for each neighbor v of u:',
      '      alt ← dist[u] + w(u, v)',
      '      if alt < dist[v]:',
      '        dist[v] ← alt',
      '        parent[v] ← u',
      '        decrease-key Q(v, alt)',
    ],
    stepToLine: { enqueue: 3, dequeue: 5, visit: 7, relax: 10, path: 6 },
    papers: [
      {
        title: 'A note on two problems in connexion with graphs',
        authors: 'Dijkstra, E. W.',
        year: 1959,
        url: 'https://link.springer.com/article/10.1007/BF01386390',
        venue: 'Numerische Mathematik 1(1)',
      },
      {
        title: 'Fibonacci heaps and their uses in improved network optimization',
        authors: 'Fredman & Tarjan',
        year: 1987,
        url: 'https://dl.acm.org/doi/10.1145/28869.28874',
        venue: 'JACM 34(3)',
      },
    ],
    proofSketch:
      "When a node u is popped from the priority queue, dist[u] is provably the shortest distance from the source. Any other path to u would have to pass through a still-pending node v with dist[v] ≥ dist[u], which contradicts the non-negative-weight assumption.",
    watchFor: [
      'No goal bias — the visited region grows isotropically. Compare to A* which biases toward G.',
      'Negative edge weights would break optimality; use Bellman-Ford instead.',
      'Watch the distance numbers on visited cells increase as the frontier expands.',
    ],
  },

  astar: {
    id: 'astar',
    name: 'A* Search',
    short: 'A*',
    family: 'Informed · Heuristic',
    complexity: { time: 'O((V + E) log V)', space: 'O(V)' },
    optimal: true,
    complete: true,
    weighted: true,
    color: 'amber',
    blurb:
      'Best-first search guided by f(n) = g(n) + h(n). Optimal when h is admissible (never overestimates).',
    pseudocode: [
      'function aStar(start, goal):',
      '  open ← min-heap; closed ← ∅',
      '  g[start] ← 0; f[start] ← h(start)',
      '  push(open, start)',
      '  while open not empty:',
      '    n ← pop min-f from open',
      '    if n = goal: return reconstruct(n)',
      '    closed.add(n)',
      '    for each neighbor m of n:',
      '      tentative ← g[n] + w(n,m)',
      '      if tentative < g[m]:',
      '        parent[m] ← n',
      '        g[m] ← tentative',
      '        f[m] ← g[m] + h(m)',
      '        if m ∉ open: push(open, m)',
    ],
    stepToLine: { enqueue: 3, dequeue: 5, visit: 7, relax: 13, path: 6, done: 6 },
    papers: [
      {
        title: 'A Formal Basis for the Heuristic Determination of Minimum Cost Paths',
        authors: 'Hart, Nilsson & Raphael',
        year: 1968,
        url: 'https://ieeexplore.ieee.org/document/4082128',
        venue: 'IEEE Trans. Syst. Sci. Cybern. 4(2)',
      },
    ],
    proofSketch:
      'A* is optimal when h is admissible (never overestimates the true cost). When the goal is popped from the open set, its f equals its true cost, since any alternative still-unexplored path has f ≥ this value.',
    watchFor: [
      'Open-set ordering: ties on f are broken by lower h — that bias toward the goal is what makes A* beat Dijkstra.',
      'If h is inadmissible (e.g. Euclidean × 1.5), the path can become non-optimal but explores fewer nodes.',
      'The heatmap overlay shows h-values: cells near G are warm, far cells are cool.',
    ],
  },

  greedy: {
    id: 'greedy',
    name: 'Greedy Best-First',
    short: 'Greedy',
    family: 'Informed · Heuristic-only',
    complexity: { time: 'O(b^d)', space: 'O(b^d)' },
    optimal: false,
    complete: false,
    weighted: false,
    color: 'pink',
    blurb:
      'Expands by lowest h(n) only — no g(n). Fast but not optimal. Good contrast with A* and Dijkstra.',
    pseudocode: [
      'function greedy(start, goal):',
      '  open ← min-heap ordered by h',
      '  open.push(start)',
      '  while open not empty:',
      '    n ← pop min-h from open',
      '    if n = goal: return reconstruct(n)',
      '    for each neighbor m of n:',
      '      if m not visited:',
      '        visited.add(m)',
      '        parent[m] ← n',
      '        open.push(m)',
    ],
    stepToLine: { enqueue: 2, dequeue: 4, visit: 6, relax: 8, path: 5 },
    papers: [],
    proofSketch:
      'Greedy best-first is not optimal because it ignores path cost. It can find a path quickly but it may not be the shortest. When the heuristic perfectly estimates the cost, greedy behaves like an oracle — but in general, it gets fooled.',
    watchFor: [
      'Fast when the heuristic is accurate, but can be wildly wrong with obstacles.',
      'No memory of cost-so-far (g) — purely guided by estimated distance to goal.',
      'Compare to A*: greedy is A* with the g-term removed.',
    ],
  },

  bidirBfs: {
    id: 'bidirBfs',
    name: 'Bidirectional BFS',
    short: 'Bidir BFS',
    family: 'Uninformed · Two-frontier',
    complexity: { time: 'O(b^(d/2))', space: 'O(b^(d/2))' },
    optimal: true,
    complete: true,
    weighted: false,
    color: 'accent',
    blurb:
      'Two BFS frontiers expanding from start and goal, meeting in the middle. Explores much less than one-directional BFS.',
    pseudocode: [
      'function bidirBfs(start, goal):',
      '  Qf ← [start]; Qb ← [goal]',
      '  visitedF ← {start}; visitedB ← {goal}',
      '  while Qf or Qb not empty:',
      '    u ← Qf.dequeue()',
      '    for each neighbor v of u:',
      '      if v in visitedB: meeting found!',
      '      visitedF.add(v); Qf.enqueue(v)',
      '    repeat symmetrically from Qb',
    ],
    stepToLine: { enqueue: 7, dequeue: 4, visit: 5, path: 6 },
    papers: [
      {
        title: 'Bi-directional A* Search',
        authors: 'Pohl, I.',
        year: 1971,
        url: 'https://www.sciencedirect.com/science/article/pii/B9780120928606500060',
        venue: 'Machine Intelligence 6',
      },
    ],
    proofSketch:
      'Bidirectional BFS meets in the middle, so each frontier only needs to travel half the distance. This reduces the search space from O(b^d) to O(b^(d/2)) — a dramatic improvement for long paths.',
    watchFor: [
      'Two frontiers (forward from S, backward from G) advancing in alternating steps.',
      'When the frontiers touch, the meeting point is found and the path is reconstructed.',
      'On unweighted grids, this cuts visited nodes roughly in half vs standard BFS.',
    ],
  },

  jps: {
    id: 'jps',
    name: 'Jump Point Search',
    short: 'JPS',
    family: 'Informed · Pruning',
    complexity: { time: 'O((V + E) log V)', space: 'O(V)' },
    optimal: true,
    complete: true,
    weighted: false,
    color: 'amber',
    blurb:
      'A* optimization for uniform-cost grids via symmetry-breaking jump points. Skips redundant paths.',
    pseudocode: [
      'function jps(start, goal):',
      '  open ← [start] keyed by f = g + h',
      '  while open not empty:',
      '    n ← pop min-f',
      '    if n = goal: return path',
      '    for each natural neighbor:',
      '      jp ← jump(n, direction)',
      '      if jp found: add to open',
    ],
    stepToLine: { enqueue: 7, dequeue: 3, visit: 5, path: 4 },
    papers: [
      {
        title: 'Online Graph Pruning for Pathfinding on Grid Maps',
        authors: 'Harabor & Grastien',
        year: 2011,
        url: 'https://users.cecs.anu.edu.au/~dharabor/data/papers/harabor-grastien-aaai11.pdf',
        venue: 'AAAI',
      },
    ],
    proofSketch:
      'JPS prunes symmetric paths by exploiting grid structure. In a uniform-cost grid, there are many paths of equal cost — JPS identifies "jump points" where symmetry breaks, visiting far fewer cells than A*.',
    watchFor: [
      'JPS skips cells that are provably not on an optimal path.',
      'Only works on uniform-cost (unweighted or uniform-weight) grids.',
      'Same optimality guarantee as A*, but dramatically fewer expansions.',
    ],
  },
};

export const ALGO_ORDER: AlgorithmId[] = ['bfs', 'dfs', 'bidirBfs', 'dijkstra', 'astar', 'greedy', 'jps'];
